[2024-05-10T14:16:16.608+0000] {processor.py:161} INFO - Started process (PID=7142) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:16:16.608+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:16:16.609+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:16:16.609+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:16:16.612+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:16:16.611+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:16:16.612+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:16:16.625+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.021 seconds
[2024-05-10T14:16:46.722+0000] {processor.py:161} INFO - Started process (PID=7151) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:16:46.723+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:16:46.724+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:16:46.724+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:16:46.726+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:16:46.725+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:16:46.726+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:16:46.739+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.021 seconds
[2024-05-10T14:17:16.831+0000] {processor.py:161} INFO - Started process (PID=7160) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:17:16.831+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:17:16.832+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:17:16.832+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:17:16.834+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:17:16.833+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:17:16.834+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:17:16.848+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.021 seconds
[2024-05-10T14:17:46.992+0000] {processor.py:161} INFO - Started process (PID=7169) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:17:46.993+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:17:46.994+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:17:46.993+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:17:46.995+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:17:46.995+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:17:46.996+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:17:47.007+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.018 seconds
[2024-05-10T14:18:17.102+0000] {processor.py:161} INFO - Started process (PID=7178) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:18:17.109+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:18:17.110+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:18:17.109+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:18:17.112+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:18:17.111+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:18:17.112+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:18:17.124+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.025 seconds
[2024-05-10T14:18:47.237+0000] {processor.py:161} INFO - Started process (PID=7187) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:18:47.237+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:18:47.238+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:18:47.238+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:18:47.240+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:18:47.240+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:18:47.240+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:18:47.253+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.020 seconds
[2024-05-10T14:19:17.374+0000] {processor.py:161} INFO - Started process (PID=7196) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:19:17.380+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:19:17.381+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:19:17.381+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:19:17.383+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:19:17.383+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:19:17.383+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:19:17.396+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.026 seconds
[2024-05-10T14:19:47.538+0000] {processor.py:161} INFO - Started process (PID=7205) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:19:47.538+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:19:47.539+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:19:47.539+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:19:47.541+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:19:47.540+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:19:47.541+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:19:47.552+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.018 seconds
[2024-05-10T14:20:17.676+0000] {processor.py:161} INFO - Started process (PID=7214) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:20:17.682+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:20:17.683+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:20:17.682+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:20:17.685+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:20:17.684+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:20:17.686+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:20:17.697+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.025 seconds
[2024-05-10T14:20:47.835+0000] {processor.py:161} INFO - Started process (PID=7223) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:20:47.841+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:20:47.842+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:20:47.842+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:20:47.844+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:20:47.843+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:20:47.844+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:20:47.856+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.025 seconds
[2024-05-10T14:21:18.008+0000] {processor.py:161} INFO - Started process (PID=7232) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:21:18.009+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:21:18.009+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:21:18.009+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:21:18.011+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:21:18.010+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:21:18.011+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:21:18.023+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.020 seconds
[2024-05-10T14:21:48.173+0000] {processor.py:161} INFO - Started process (PID=7241) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:21:48.179+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:21:48.179+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:21:48.179+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:21:48.181+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:21:48.181+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:21:48.181+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:21:48.193+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.024 seconds
[2024-05-10T14:22:18.305+0000] {processor.py:161} INFO - Started process (PID=7250) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:22:18.305+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:22:18.306+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:22:18.306+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:22:18.308+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:22:18.308+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:22:18.309+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:22:18.321+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.020 seconds
[2024-05-10T14:22:48.467+0000] {processor.py:161} INFO - Started process (PID=7259) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:22:48.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:22:48.473+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:22:48.473+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:22:48.476+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:22:48.475+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:22:48.476+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:22:48.488+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.025 seconds
[2024-05-10T14:23:18.636+0000] {processor.py:161} INFO - Started process (PID=7268) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:23:18.636+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:23:18.637+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:23:18.637+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:23:18.639+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:23:18.638+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:23:18.639+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:23:18.652+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.019 seconds
[2024-05-10T14:23:48.791+0000] {processor.py:161} INFO - Started process (PID=7277) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:23:48.797+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:23:48.797+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:23:48.797+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:23:48.799+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:23:48.799+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:23:48.800+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:23:48.811+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.024 seconds
[2024-05-10T14:24:18.919+0000] {processor.py:161} INFO - Started process (PID=7286) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:24:18.920+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:24:18.920+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:24:18.920+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:24:18.922+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:24:18.921+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:24:18.922+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:24:18.934+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.018 seconds
[2024-05-10T14:24:49.046+0000] {processor.py:161} INFO - Started process (PID=7295) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:24:49.052+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:24:49.053+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:24:49.053+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:24:49.055+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:24:49.054+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:24:49.055+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:24:49.067+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.024 seconds
[2024-05-10T14:25:19.217+0000] {processor.py:161} INFO - Started process (PID=7304) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:25:19.224+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:25:19.224+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:25:19.224+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:25:19.226+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:25:19.225+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:25:19.226+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:25:19.238+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.025 seconds
[2024-05-10T14:25:49.351+0000] {processor.py:161} INFO - Started process (PID=7313) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:25:49.352+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:25:49.353+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:25:49.352+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:25:49.355+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:25:49.354+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:25:49.355+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:25:49.366+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.019 seconds
[2024-05-10T14:26:19.493+0000] {processor.py:161} INFO - Started process (PID=7322) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:26:19.499+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:26:19.500+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:26:19.500+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:26:19.502+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:26:19.501+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:26:19.502+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:26:19.514+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.025 seconds
[2024-05-10T14:26:49.655+0000] {processor.py:161} INFO - Started process (PID=7331) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:26:49.655+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:26:49.656+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:26:49.656+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:26:49.658+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:26:49.657+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:26:49.658+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:26:49.670+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.018 seconds
[2024-05-10T14:27:19.790+0000] {processor.py:161} INFO - Started process (PID=7340) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:27:19.796+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:27:19.796+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:27:19.796+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:27:19.798+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:27:19.798+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:27:19.798+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:27:19.810+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.024 seconds
[2024-05-10T14:27:49.948+0000] {processor.py:161} INFO - Started process (PID=7349) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:27:49.949+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:27:49.949+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:27:49.949+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:27:49.951+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:27:49.950+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:27:49.951+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:27:49.963+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.019 seconds
[2024-05-10T14:28:20.078+0000] {processor.py:161} INFO - Started process (PID=7358) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:28:20.079+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:28:20.079+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:28:20.079+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:28:20.081+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:28:20.080+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:28:20.081+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:28:20.093+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.018 seconds
[2024-05-10T14:28:50.208+0000] {processor.py:161} INFO - Started process (PID=7367) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:28:50.214+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:28:50.215+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:28:50.215+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:28:50.217+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:28:50.216+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:28:50.217+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:28:50.228+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.024 seconds
[2024-05-10T14:29:20.374+0000] {processor.py:161} INFO - Started process (PID=7376) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:29:20.375+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:29:20.375+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:29:20.375+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:29:20.377+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:29:20.377+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:29:20.378+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:29:20.390+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.020 seconds
[2024-05-10T14:29:50.513+0000] {processor.py:161} INFO - Started process (PID=7385) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:29:50.514+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:29:50.515+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:29:50.514+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:29:50.516+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:29:50.516+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:29:50.517+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:29:50.529+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.020 seconds
[2024-05-10T14:30:20.637+0000] {processor.py:161} INFO - Started process (PID=7394) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:30:20.638+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:30:20.638+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:30:20.638+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:30:20.641+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:30:20.640+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:30:20.641+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:30:20.654+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.021 seconds
[2024-05-10T14:30:50.765+0000] {processor.py:161} INFO - Started process (PID=7403) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:30:50.771+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:30:50.772+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:30:50.771+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:30:50.774+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:30:50.773+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:30:50.774+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:30:50.785+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.023 seconds
[2024-05-10T14:31:20.900+0000] {processor.py:161} INFO - Started process (PID=7412) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:31:20.900+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:31:20.901+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:31:20.900+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:31:20.903+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:31:20.902+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:31:20.903+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:31:20.915+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.020 seconds
[2024-05-10T14:31:51.024+0000] {processor.py:161} INFO - Started process (PID=7421) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:31:51.030+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:31:51.031+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:31:51.030+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:31:51.033+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:31:51.032+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:31:51.033+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:31:51.045+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.026 seconds
[2024-05-10T14:33:15.773+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:33:15.773+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:33:15.774+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:33:15.774+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:33:15.777+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:33:15.776+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:33:15.777+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:33:15.790+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.022 seconds
[2024-05-10T14:33:45.905+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:33:45.906+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:33:45.907+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:33:45.906+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:33:45.908+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:33:45.908+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:33:45.909+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:33:45.921+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.019 seconds
[2024-05-10T14:34:16.031+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:34:16.037+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:34:16.039+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:34:16.038+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:34:16.041+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:34:16.040+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:34:16.041+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:34:16.054+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.026 seconds
[2024-05-10T14:36:35.512+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:36:35.512+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:36:35.513+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:36:35.513+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:36:35.515+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:36:35.514+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:36:35.515+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:36:35.530+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.022 seconds
[2024-05-10T14:37:05.641+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:37:05.641+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:37:05.642+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:37:05.642+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:37:05.644+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:37:05.643+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:37:05.644+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:37:05.655+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.017 seconds
[2024-05-10T14:37:35.807+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:37:35.807+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:37:35.809+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:37:35.808+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:37:35.810+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:37:35.810+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:37:35.811+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:37:35.822+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.018 seconds
[2024-05-10T14:38:28.274+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:38:28.274+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:38:28.275+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:38:28.275+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:38:28.277+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:38:28.276+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:38:28.277+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:38:28.290+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.019 seconds
[2024-05-10T14:38:58.576+0000] {processor.py:161} INFO - Started process (PID=49) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:38:58.576+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:38:58.577+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:38:58.577+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:38:58.579+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:38:58.578+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 11
    ) as dag:
             ^
IndentationError: expected an indented block after 'with' statement on line 6
[2024-05-10T14:38:58.580+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:38:58.590+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.018 seconds
[2024-05-10T14:45:36.315+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:45:36.315+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:45:36.317+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:45:36.316+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:45:36.319+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:45:36.318+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 2, in <module>
    from steps.get_odds_history import parser
ModuleNotFoundError: No module named 'steps.get_odds_history'
[2024-05-10T14:45:36.319+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:45:36.333+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.022 seconds
[2024-05-10T14:46:06.445+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:46:06.446+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:46:06.447+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:46:06.447+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:46:06.449+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:46:06.448+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 2, in <module>
    from steps.get_odds_history import parser
ModuleNotFoundError: No module named 'steps.get_odds_history'
[2024-05-10T14:46:06.449+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:46:06.461+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.019 seconds
[2024-05-10T14:46:36.563+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:46:36.564+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:46:36.565+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:46:36.564+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:46:36.567+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:46:36.566+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 2, in <module>
    from steps.get_odds_history import parser
ModuleNotFoundError: No module named 'steps.get_odds_history'
[2024-05-10T14:46:36.567+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:46:36.578+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.018 seconds
[2024-05-10T14:47:06.742+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:47:06.743+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:47:06.744+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:47:06.744+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:47:06.746+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:47:06.745+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 2, in <module>
    from steps.get_odds_history import parser
ModuleNotFoundError: No module named 'steps.get_odds_history'
[2024-05-10T14:47:06.746+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:47:06.759+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.020 seconds
[2024-05-10T14:48:11.865+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:48:11.866+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:48:11.867+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:48:11.867+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:48:11.869+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:48:11.869+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 2, in <module>
    from steps.get_odds_history import parser
ModuleNotFoundError: No module named 'steps.get_odds_history'
[2024-05-10T14:48:11.870+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:48:11.884+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.024 seconds
[2024-05-10T14:48:41.999+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:48:41.999+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:48:42.000+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:48:42.000+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:48:42.002+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:48:42.001+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 2, in <module>
    from steps.get_odds_history import parser
ModuleNotFoundError: No module named 'steps.get_odds_history'
[2024-05-10T14:48:42.002+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:48:42.013+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.018 seconds
[2024-05-10T14:49:12.116+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:49:12.116+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:49:12.117+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:49:12.117+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:49:12.121+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:49:12.119+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 2, in <module>
    from steps.get_odds_history import parser
ModuleNotFoundError: No module named 'steps.get_odds_history'
[2024-05-10T14:49:12.122+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:49:12.132+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.019 seconds
[2024-05-10T14:49:42.237+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:49:42.238+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:49:42.239+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:49:42.239+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:49:42.241+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:49:42.240+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 2, in <module>
    from steps.get_odds_history import parser
ModuleNotFoundError: No module named 'steps.get_odds_history'
[2024-05-10T14:49:42.241+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:49:42.252+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.018 seconds
[2024-05-10T14:50:12.363+0000] {processor.py:161} INFO - Started process (PID=75) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:50:12.364+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:50:12.365+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:50:12.365+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:50:12.367+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:50:12.366+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 2, in <module>
    from steps.get_odds_history import parser
ModuleNotFoundError: No module named 'steps.get_odds_history'
[2024-05-10T14:50:12.367+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:50:12.378+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.019 seconds
[2024-05-10T14:50:22.431+0000] {processor.py:161} INFO - Started process (PID=78) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:50:22.431+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:50:22.432+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:50:22.432+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:50:22.434+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:50:22.434+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 2, in <module>
    from steps.get_odds_history import parser
ModuleNotFoundError: No module named 'steps.get_odds_history'
[2024-05-10T14:50:22.435+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:50:22.446+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.019 seconds
[2024-05-10T14:51:14.580+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:51:14.581+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:51:14.582+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:51:14.582+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:51:14.585+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:51:14.584+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 2, in <module>
    from steps.get_odds_history import parser
ModuleNotFoundError: No module named 'steps.get_odds_history'
[2024-05-10T14:51:14.585+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:51:14.599+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.022 seconds
[2024-05-10T14:51:44.712+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:51:44.713+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:51:44.714+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:51:44.713+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:51:44.715+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:51:44.715+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 2, in <module>
    from steps.get_odds_history import parser
ModuleNotFoundError: No module named 'steps.get_odds_history'
[2024-05-10T14:51:44.716+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:51:44.726+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.018 seconds
[2024-05-10T14:52:14.874+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:52:14.874+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:52:14.878+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:52:14.877+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:52:14.880+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:52:14.879+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 2, in <module>
    from steps.get_odds_history import parser
ModuleNotFoundError: No module named 'steps.get_odds_history'
[2024-05-10T14:52:14.880+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:52:14.890+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.020 seconds
[2024-05-10T14:52:45.042+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:52:45.043+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:52:45.044+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:52:45.044+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:52:45.046+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:52:45.045+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 2, in <module>
    from steps.get_odds_history import parser
ModuleNotFoundError: No module named 'steps.get_odds_history'
[2024-05-10T14:52:45.046+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:52:45.057+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.018 seconds
[2024-05-10T14:53:15.212+0000] {processor.py:161} INFO - Started process (PID=75) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:53:15.218+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:53:15.220+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:53:15.219+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:53:15.222+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:53:15.221+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 2, in <module>
    from steps.get_odds_history import parser
ModuleNotFoundError: No module named 'steps.get_odds_history'
[2024-05-10T14:53:15.222+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:53:15.233+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.024 seconds
[2024-05-10T14:53:45.339+0000] {processor.py:161} INFO - Started process (PID=84) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:53:45.339+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:53:45.341+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:53:45.341+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:53:45.343+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:53:45.342+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 2, in <module>
    from steps.get_odds_history import parser
ModuleNotFoundError: No module named 'steps.get_odds_history'
[2024-05-10T14:53:45.343+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:53:45.354+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.019 seconds
[2024-05-10T14:54:15.464+0000] {processor.py:161} INFO - Started process (PID=93) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:54:15.464+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:54:15.465+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:54:15.465+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:54:15.467+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:54:15.467+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 2, in <module>
    from steps.get_odds_history import parser
ModuleNotFoundError: No module named 'steps.get_odds_history'
[2024-05-10T14:54:15.467+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:54:15.480+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.019 seconds
[2024-05-10T14:54:45.595+0000] {processor.py:161} INFO - Started process (PID=102) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:54:45.598+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:54:45.599+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:54:45.599+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:54:45.601+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:54:45.601+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/get_odds_history.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_odds_history.py", line 2, in <module>
    from steps.get_odds_history import parser
ModuleNotFoundError: No module named 'steps.get_odds_history'
[2024-05-10T14:54:45.602+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:54:45.612+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.021 seconds
[2024-05-10T14:54:46.627+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:54:46.627+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:54:46.628+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:54:46.628+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:54:46.634+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:54:46.705+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:54:46.705+0000] {override.py:1829} INFO - Created Permission View: can read on DAG:get_odds_history
[2024-05-10T14:54:46.710+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:54:46.710+0000] {override.py:1829} INFO - Created Permission View: can edit on DAG:get_odds_history
[2024-05-10T14:54:46.713+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:54:46.713+0000] {override.py:1829} INFO - Created Permission View: can delete on DAG:get_odds_history
[2024-05-10T14:54:46.713+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:54:46.713+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T14:54:46.720+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:54:46.720+0000] {dag.py:3118} INFO - Creating ORM DAG for get_odds_history
[2024-05-10T14:54:46.725+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:54:46.725+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to 2023-01-01 00:00:00+00:00, run_after=2023-01-01 00:00:00+00:00
[2024-05-10T14:54:46.733+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.110 seconds
[2024-05-10T14:55:33.460+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:55:33.460+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:55:33.462+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:55:33.461+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:55:33.470+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:55:33.624+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:55:33.624+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T14:55:33.636+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:55:33.636+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to 2023-01-01 00:00:00+00:00, run_after=2023-01-01 00:00:00+00:00
[2024-05-10T14:55:33.646+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.190 seconds
[2024-05-10T14:56:03.765+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:56:03.766+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:56:03.767+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:56:03.766+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:56:03.772+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:56:03.790+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:56:03.789+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T14:56:03.802+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:56:03.801+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T14:56:03.811+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.049 seconds
[2024-05-10T14:56:33.920+0000] {processor.py:161} INFO - Started process (PID=61) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:56:33.927+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:56:33.928+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:56:33.927+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:56:33.934+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:56:33.950+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:56:33.950+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T14:56:33.961+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:56:33.961+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T14:56:33.970+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.053 seconds
[2024-05-10T14:57:04.075+0000] {processor.py:161} INFO - Started process (PID=70) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:57:04.076+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:57:04.077+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:57:04.077+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:57:04.082+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:57:04.099+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:57:04.099+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T14:57:04.111+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:57:04.111+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T14:57:04.120+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.048 seconds
[2024-05-10T14:57:34.231+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:57:34.231+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:57:34.233+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:57:34.232+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:57:34.237+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:57:34.254+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:57:34.254+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T14:57:34.267+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:57:34.266+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T14:57:34.276+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.049 seconds
[2024-05-10T14:58:48.698+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:58:48.699+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:58:48.700+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:58:48.700+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:58:48.710+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:58:48.899+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:58:48.898+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T14:58:48.911+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:58:48.911+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T14:58:48.922+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.227 seconds
[2024-05-10T14:59:19.037+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:59:19.038+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:59:19.039+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:59:19.039+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:59:19.044+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:59:19.066+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:59:19.066+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T14:59:19.079+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:59:19.079+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T14:59:19.088+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.055 seconds
[2024-05-10T14:59:49.202+0000] {processor.py:161} INFO - Started process (PID=56) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:59:49.208+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T14:59:49.210+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:59:49.209+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:59:49.216+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T14:59:49.231+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:59:49.231+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T14:59:49.243+0000] {logging_mixin.py:188} INFO - [2024-05-10T14:59:49.243+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T14:59:49.252+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.053 seconds
[2024-05-10T15:00:19.361+0000] {processor.py:161} INFO - Started process (PID=65) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:00:19.362+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:00:19.363+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:00:19.363+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:00:19.367+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:00:19.383+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:00:19.383+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:00:19.395+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:00:19.395+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:00:19.404+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.046 seconds
[2024-05-10T15:01:51.681+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:01:51.682+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:01:51.683+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:01:51.683+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:01:51.691+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:01:51.852+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:01:51.852+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:01:51.865+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:01:51.865+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:01:51.876+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.199 seconds
[2024-05-10T15:02:21.990+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:02:21.990+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:02:21.992+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:02:21.991+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:02:21.997+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:02:22.015+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:02:22.015+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:02:22.027+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:02:22.027+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:02:22.037+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.050 seconds
[2024-05-10T15:02:52.152+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:02:52.152+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:02:52.157+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:02:52.157+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:02:52.162+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:02:52.181+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:02:52.181+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:02:52.195+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:02:52.194+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:02:52.204+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.056 seconds
[2024-05-10T15:03:02.039+0000] {processor.py:161} INFO - Started process (PID=60) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:03:02.040+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:03:02.041+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:03:02.040+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:03:02.046+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:03:02.061+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:03:02.061+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'get_odds_history', 'Task Id': 'parser', 'Run Id': 'manual__2024-05-10T14:55:47.337263+00:00', 'Hostname': '801d2bebd4d9', 'External Executor Id': '0a0f44f6-4027-452c-abeb-c78f3edf7ca1'}
[2024-05-10T15:03:02.070+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:03:02.070+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=get_odds_history, task_id=parser, execution_date=20240510T145547, start_date=20240510T145549, end_date=20240510T150302
[2024-05-10T15:03:02.075+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: get_odds_history.parser manual__2024-05-10T14:55:47.337263+00:00 [failed]> in state failed
[2024-05-10T15:03:02.085+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:03:02.085+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:03:02.096+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:03:02.096+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:03:02.104+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.069 seconds
[2024-05-10T15:03:12.095+0000] {processor.py:161} INFO - Started process (PID=67) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:03:12.096+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:03:12.097+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:03:12.097+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:03:12.102+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:03:12.119+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:03:12.119+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'get_odds_history', 'Task Id': 'parser', 'Run Id': 'scheduled__2023-01-01T00:00:00+00:00', 'Hostname': '801d2bebd4d9', 'External Executor Id': 'a0697a86-99da-4e16-a6ef-c8b81e037ee9'}
[2024-05-10T15:03:12.128+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:03:12.128+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=get_odds_history, task_id=parser, execution_date=20230101T000000, start_date=20240510T145549, end_date=20240510T150312
[2024-05-10T15:03:12.133+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: get_odds_history.parser scheduled__2023-01-01T00:00:00+00:00 [failed]> in state failed
[2024-05-10T15:03:12.134+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:03:12.134+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'get_odds_history', 'Task Id': 'parser', 'Run Id': 'scheduled__2023-01-01T00:00:00+00:00', 'Hostname': '801d2bebd4d9', 'External Executor Id': 'a0697a86-99da-4e16-a6ef-c8b81e037ee9'}
[2024-05-10T15:03:12.138+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:03:12.137+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=get_odds_history, task_id=parser, execution_date=20230101T000000, start_date=20240510T145549, end_date=20240510T150312
[2024-05-10T15:03:12.139+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: get_odds_history.parser scheduled__2023-01-01T00:00:00+00:00 [failed]> in state failed
[2024-05-10T15:03:12.150+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:03:12.150+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:03:12.161+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:03:12.161+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:03:12.169+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.077 seconds
[2024-05-10T15:03:42.202+0000] {processor.py:161} INFO - Started process (PID=76) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:03:42.203+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:03:42.204+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:03:42.204+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:03:42.209+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:03:42.226+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:03:42.226+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:03:42.239+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:03:42.238+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:03:42.248+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.050 seconds
[2024-05-10T15:04:12.414+0000] {processor.py:161} INFO - Started process (PID=85) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:04:12.414+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:04:12.416+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:04:12.415+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:04:12.420+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:04:12.436+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:04:12.436+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:04:12.449+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:04:12.449+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:04:12.459+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.049 seconds
[2024-05-10T15:04:42.556+0000] {processor.py:161} INFO - Started process (PID=94) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:04:42.557+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:04:42.558+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:04:42.558+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:04:42.563+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:04:42.580+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:04:42.580+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:04:42.593+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:04:42.593+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:04:42.601+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.049 seconds
[2024-05-10T15:05:12.694+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:05:12.694+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:05:12.695+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:05:12.695+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:05:12.701+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:05:12.717+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:05:12.717+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:05:12.730+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:05:12.730+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:05:12.740+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.049 seconds
[2024-05-10T15:05:42.870+0000] {processor.py:161} INFO - Started process (PID=112) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:05:42.876+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:05:42.877+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:05:42.877+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:05:42.882+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:05:42.898+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:05:42.898+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:05:42.911+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:05:42.910+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:05:42.919+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.052 seconds
[2024-05-10T15:05:52.762+0000] {processor.py:161} INFO - Started process (PID=113) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:05:52.762+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:05:52.763+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:05:52.763+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:05:52.767+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:05:52.782+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:05:52.781+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'get_odds_history', 'Task Id': 'parser', 'Run Id': 'manual__2024-05-10T14:59:12.537036+00:00', 'Hostname': '25cebcbccb97', 'External Executor Id': '08df657e-f537-40a0-8646-be0eb9b3188f'}
[2024-05-10T15:05:52.789+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:05:52.789+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=get_odds_history, task_id=parser, execution_date=20240510T145912, start_date=20240510T145914, end_date=20240510T150552
[2024-05-10T15:05:52.794+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: get_odds_history.parser manual__2024-05-10T14:59:12.537036+00:00 [failed]> in state failed
[2024-05-10T15:05:52.804+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:05:52.804+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:05:52.814+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:05:52.814+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:05:52.823+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.065 seconds
[2024-05-10T15:06:02.805+0000] {processor.py:161} INFO - Started process (PID=116) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:06:02.806+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:06:02.807+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:06:02.807+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:06:02.812+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:06:02.827+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:06:02.827+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'get_odds_history', 'Task Id': 'parser', 'Run Id': 'manual__2024-05-10T14:59:24.421147+00:00', 'Hostname': '25cebcbccb97', 'External Executor Id': '4fc5745c-3fea-49b8-9bad-36b9afd5281f'}
[2024-05-10T15:06:02.835+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:06:02.835+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=get_odds_history, task_id=parser, execution_date=20240510T145924, start_date=20240510T145925, end_date=20240510T150602
[2024-05-10T15:06:02.840+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: get_odds_history.parser manual__2024-05-10T14:59:24.421147+00:00 [failed]> in state failed
[2024-05-10T15:06:02.841+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:06:02.841+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'get_odds_history', 'Task Id': 'parser', 'Run Id': 'manual__2024-05-10T14:59:24.421147+00:00', 'Hostname': '25cebcbccb97', 'External Executor Id': '4fc5745c-3fea-49b8-9bad-36b9afd5281f'}
[2024-05-10T15:06:02.844+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:06:02.844+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=get_odds_history, task_id=parser, execution_date=20240510T145924, start_date=20240510T145925, end_date=20240510T150602
[2024-05-10T15:06:02.845+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: get_odds_history.parser manual__2024-05-10T14:59:24.421147+00:00 [failed]> in state failed
[2024-05-10T15:06:02.856+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:06:02.856+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:06:02.867+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:06:02.867+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:06:02.875+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.073 seconds
[2024-05-10T15:07:01.063+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:07:01.064+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:07:01.065+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:07:01.065+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:07:01.075+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:07:01.238+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:07:01.238+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:07:01.250+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:07:01.250+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:07:01.260+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.201 seconds
[2024-05-10T15:07:31.383+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:07:31.383+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:07:31.385+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:07:31.384+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:07:31.390+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:07:31.408+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:07:31.408+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:07:31.420+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:07:31.420+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:07:31.429+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.050 seconds
[2024-05-10T15:08:01.546+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:08:01.547+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:08:01.548+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:08:01.548+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:08:01.555+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:08:01.571+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:08:01.570+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:08:01.582+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:08:01.582+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:08:01.591+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.048 seconds
[2024-05-10T15:08:31.705+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:08:31.705+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:08:31.707+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:08:31.707+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:08:31.712+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:08:31.729+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:08:31.729+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:08:31.743+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:08:31.743+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:08:31.753+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.052 seconds
[2024-05-10T15:09:01.869+0000] {processor.py:161} INFO - Started process (PID=75) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:09:01.875+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:09:01.877+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:09:01.877+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:09:01.882+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:09:01.900+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:09:01.899+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:09:01.912+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:09:01.912+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:09:01.922+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.057 seconds
[2024-05-10T15:09:32.035+0000] {processor.py:161} INFO - Started process (PID=84) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:09:32.036+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:09:32.037+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:09:32.037+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:09:32.042+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:09:32.060+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:09:32.060+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:09:32.074+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:09:32.074+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:09:32.083+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.051 seconds
[2024-05-10T15:10:02.195+0000] {processor.py:161} INFO - Started process (PID=93) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:10:02.201+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:10:02.202+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:10:02.202+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:10:02.207+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:10:02.223+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:10:02.223+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:10:02.235+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:10:02.235+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:10:02.245+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.053 seconds
[2024-05-10T15:10:32.358+0000] {processor.py:161} INFO - Started process (PID=102) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:10:32.359+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:10:32.360+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:10:32.360+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:10:32.365+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:10:32.383+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:10:32.383+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:10:32.396+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:10:32.396+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:10:32.405+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.051 seconds
[2024-05-10T15:11:02.519+0000] {processor.py:161} INFO - Started process (PID=111) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:11:02.525+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:11:02.526+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:11:02.526+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:11:02.531+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:11:02.548+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:11:02.547+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:11:02.560+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:11:02.560+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:11:02.570+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.055 seconds
[2024-05-10T15:11:22.033+0000] {processor.py:161} INFO - Started process (PID=120) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:11:22.033+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:11:22.034+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:11:22.034+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:11:22.040+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:11:22.057+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:11:22.057+0000] {taskinstance.py:2892} ERROR - {'DAG Id': 'get_odds_history', 'Task Id': 'parser', 'Run Id': 'manual__2024-05-10T15:02:03.096448+00:00', 'Hostname': '0f53cf84ff74', 'External Executor Id': '548268c8-707d-465b-b7aa-248eb4589c10'}
[2024-05-10T15:11:22.065+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:11:22.065+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=get_odds_history, task_id=parser, execution_date=20240510T150203, start_date=20240510T150205, end_date=20240510T151122
[2024-05-10T15:11:22.070+0000] {processor.py:791} INFO - Executed failure callback for <TaskInstance: get_odds_history.parser manual__2024-05-10T15:02:03.096448+00:00 [failed]> in state failed
[2024-05-10T15:11:22.080+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:11:22.080+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:11:22.090+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:11:22.090+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:11:22.098+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.070 seconds
[2024-05-10T15:11:52.142+0000] {processor.py:161} INFO - Started process (PID=129) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:11:52.143+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:11:52.144+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:11:52.144+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:11:52.148+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:11:52.165+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:11:52.165+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:11:52.178+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:11:52.177+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:11:52.187+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.049 seconds
[2024-05-10T15:12:22.292+0000] {processor.py:161} INFO - Started process (PID=138) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:12:22.293+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:12:22.294+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:12:22.294+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:12:22.299+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:12:22.316+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:12:22.316+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:12:22.331+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:12:22.330+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:12:22.341+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.052 seconds
[2024-05-10T15:12:52.488+0000] {processor.py:161} INFO - Started process (PID=147) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:12:52.494+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:12:52.495+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:12:52.495+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:12:52.500+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:12:52.516+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:12:52.516+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:12:52.529+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:12:52.529+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:12:52.538+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.054 seconds
[2024-05-10T15:13:22.635+0000] {processor.py:161} INFO - Started process (PID=156) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:13:22.636+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:13:22.637+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:13:22.637+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:13:22.642+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:13:22.659+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:13:22.659+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:13:22.672+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:13:22.671+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:13:22.681+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.049 seconds
[2024-05-10T15:13:52.787+0000] {processor.py:161} INFO - Started process (PID=165) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:13:52.788+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:13:52.789+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:13:52.789+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:13:52.794+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:13:52.811+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:13:52.811+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:13:52.824+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:13:52.824+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:13:52.833+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.049 seconds
[2024-05-10T15:14:22.930+0000] {processor.py:161} INFO - Started process (PID=174) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:14:22.936+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:14:22.938+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:14:22.937+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:14:22.942+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:14:22.959+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:14:22.959+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:14:22.971+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:14:22.971+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:14:22.980+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.054 seconds
[2024-05-10T15:14:53.119+0000] {processor.py:161} INFO - Started process (PID=183) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:14:53.135+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:14:53.136+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:14:53.136+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:14:53.142+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:14:53.160+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:14:53.160+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:14:53.180+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:14:53.179+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:14:53.193+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.078 seconds
[2024-05-10T15:15:23.288+0000] {processor.py:161} INFO - Started process (PID=192) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:15:23.294+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:15:23.295+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:15:23.295+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:15:23.300+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:15:23.317+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:15:23.317+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:15:23.330+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:15:23.330+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:15:23.338+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.054 seconds
[2024-05-10T15:15:53.432+0000] {processor.py:161} INFO - Started process (PID=201) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:15:53.438+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:15:53.440+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:15:53.439+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:15:53.445+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:15:53.463+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:15:53.463+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:15:53.478+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:15:53.477+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:15:53.488+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.060 seconds
[2024-05-10T15:16:23.599+0000] {processor.py:161} INFO - Started process (PID=210) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:16:23.606+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:16:23.607+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:16:23.607+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:16:23.612+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:16:23.629+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:16:23.629+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:16:23.642+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:16:23.642+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:16:23.651+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.055 seconds
[2024-05-10T15:16:53.749+0000] {processor.py:161} INFO - Started process (PID=219) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:16:53.755+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:16:53.757+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:16:53.756+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:16:53.761+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:16:53.777+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:16:53.777+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:16:53.790+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:16:53.790+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:16:53.799+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.053 seconds
[2024-05-10T15:17:23.947+0000] {processor.py:161} INFO - Started process (PID=228) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:17:23.953+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:17:23.954+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:17:23.954+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:17:23.959+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:17:23.975+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:17:23.975+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:17:23.987+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:17:23.987+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:17:23.996+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.053 seconds
[2024-05-10T15:17:54.096+0000] {processor.py:161} INFO - Started process (PID=237) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:17:54.111+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:17:54.113+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:17:54.113+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:17:54.118+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:17:54.135+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:17:54.135+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:17:54.147+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:17:54.147+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:17:54.156+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.064 seconds
[2024-05-10T15:18:24.253+0000] {processor.py:161} INFO - Started process (PID=246) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:18:24.254+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:18:24.255+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:18:24.255+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:18:24.260+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:18:24.275+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:18:24.275+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:18:24.287+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:18:24.287+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:18:24.296+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.046 seconds
[2024-05-10T15:18:54.392+0000] {processor.py:161} INFO - Started process (PID=255) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:18:54.398+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:18:54.400+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:18:54.400+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:18:54.405+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:18:54.421+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:18:54.421+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:18:54.434+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:18:54.434+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:18:54.444+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.056 seconds
[2024-05-10T15:19:24.542+0000] {processor.py:161} INFO - Started process (PID=264) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:19:24.548+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:19:24.550+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:19:24.550+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:19:24.555+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:19:24.571+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:19:24.571+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:19:24.583+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:19:24.583+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:19:24.592+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.054 seconds
[2024-05-10T15:19:54.689+0000] {processor.py:161} INFO - Started process (PID=273) to work on /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:19:54.695+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_odds_history.py for tasks to queue
[2024-05-10T15:19:54.697+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:19:54.697+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:19:54.701+0000] {processor.py:840} INFO - DAG(s) 'get_odds_history' retrieved from /opt/airflow/dags/get_odds_history.py
[2024-05-10T15:19:54.717+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:19:54.717+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-10T15:19:54.728+0000] {logging_mixin.py:188} INFO - [2024-05-10T15:19:54.728+0000] {dag.py:3954} INFO - Setting next_dagrun for get_odds_history to None, run_after=None
[2024-05-10T15:19:54.737+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_odds_history.py took 0.051 seconds
