[2024-05-21T18:22:10.633+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-21T18:22:10.646+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: games.load_data manual__2024-05-21T18:17:58.760441+00:00 [queued]>
[2024-05-21T18:22:10.651+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: games.load_data manual__2024-05-21T18:17:58.760441+00:00 [queued]>
[2024-05-21T18:22:10.651+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-21T18:22:10.659+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_data> on 2024-05-21 18:17:58.760441+00:00
[2024-05-21T18:22:10.666+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=128) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-21T18:22:10.667+0000] {standard_task_runner.py:63} INFO - Started process 130 to run task
[2024-05-21T18:22:10.667+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'games', 'load_data', 'manual__2024-05-21T18:17:58.760441+00:00', '--job-id', '546', '--raw', '--subdir', 'DAGS_FOLDER/get_main_games.py', '--cfg-path', '/tmp/tmp2wl02__c']
[2024-05-21T18:22:10.668+0000] {standard_task_runner.py:91} INFO - Job 546: Subtask load_data
[2024-05-21T18:22:10.696+0000] {task_command.py:426} INFO - Running <TaskInstance: games.load_data manual__2024-05-21T18:17:58.760441+00:00 [running]> on host 4010141b380c
[2024-05-21T18:22:10.749+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='games' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T18:17:58.760441+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-21T18:17:58.760441+00:00'
[2024-05-21T18:22:10.749+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-21T18:22:10.778+0000] {warnings.py:110} WARNING - /opt/***/plugins/steps/get_matches.py:146: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_json(df_json)

[2024-05-21T18:22:10.858+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2024-05-21T18:22:11.159+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-21T18:22:11.159+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/steps/get_matches.py", line 149, in load_data
    hook.insert_rows(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 571, in insert_rows
    sql = self._generate_insert_sql(table, values, target_fields, replace, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 302, in _generate_insert_sql
    target_fields_fragment = ", ".join(target_fields)
                             ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, int found
[2024-05-21T18:22:11.167+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=games, task_id=load_data, execution_date=20240521T181758, start_date=20240521T182210, end_date=20240521T182211
[2024-05-21T18:22:11.175+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 546 for task load_data (sequence item 0: expected str instance, int found; 130)
[2024-05-21T18:22:11.200+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-21T18:22:11.211+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-21T18:22:11.212+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
